/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Point from './Point';

/**
 * The DataBody model module.
 * @module model/DataBody
 * @version TEL-1.2.5
 */
class DataBody {
    /**
     * Constructs a new <code>DataBody</code>.
     * @alias module:model/DataBody
     * @param telemetryId {String} telemetryId
     * @param point {module:model/Point} 
     */
    constructor(telemetryId, point) { 
        
        DataBody.initialize(this, telemetryId, point);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, telemetryId, point) { 
        obj['telemetryId'] = telemetryId;
        obj['point'] = point;
    }

    /**
     * Constructs a <code>DataBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DataBody} obj Optional instance to populate.
     * @return {module:model/DataBody} The populated <code>DataBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataBody();

            if (data.hasOwnProperty('telemetryId')) {
                obj['telemetryId'] = ApiClient.convertToType(data['telemetryId'], 'String');
            }
            if (data.hasOwnProperty('point')) {
                obj['point'] = Point.constructFromObject(data['point']);
            }
        }
        return obj;
    }


}

/**
 * telemetryId
 * @member {String} telemetryId
 */
DataBody.prototype['telemetryId'] = undefined;

/**
 * @member {module:model/Point} point
 */
DataBody.prototype['point'] = undefined;






export default DataBody;

