/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StartBody model module.
 * @module model/StartBody
 * @version TEL-1.2.5
 */
class StartBody {
    /**
     * Constructs a new <code>StartBody</code>.
     * @alias module:model/StartBody
     * @param aircraftId {String} Aircraft id to link your telemetry
     * @param trackerId {String} Tracker id to link your telemetry
     */
    constructor(aircraftId, trackerId) { 
        
        StartBody.initialize(this, aircraftId, trackerId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, aircraftId, trackerId) { 
        obj['aircraftId'] = aircraftId;
        obj['trackerId'] = trackerId;
    }

    /**
     * Constructs a <code>StartBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StartBody} obj Optional instance to populate.
     * @return {module:model/StartBody} The populated <code>StartBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StartBody();

            if (data.hasOwnProperty('aircraftId')) {
                obj['aircraftId'] = ApiClient.convertToType(data['aircraftId'], 'String');
            }
            if (data.hasOwnProperty('trackerId')) {
                obj['trackerId'] = ApiClient.convertToType(data['trackerId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Aircraft id to link your telemetry
 * @member {String} aircraftId
 */
StartBody.prototype['aircraftId'] = undefined;

/**
 * Tracker id to link your telemetry
 * @member {String} trackerId
 */
StartBody.prototype['trackerId'] = undefined;






export default StartBody;

