/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StopBody model module.
 * @module model/StopBody
 * @version TEL-1.2.5
 */
class StopBody {
    /**
     * Constructs a new <code>StopBody</code>.
     * @alias module:model/StopBody
     * @param telemetryId {String} telemetryId
     */
    constructor(telemetryId) { 
        
        StopBody.initialize(this, telemetryId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, telemetryId) { 
        obj['telemetryId'] = telemetryId;
    }

    /**
     * Constructs a <code>StopBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StopBody} obj Optional instance to populate.
     * @return {module:model/StopBody} The populated <code>StopBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StopBody();

            if (data.hasOwnProperty('telemetryId')) {
                obj['telemetryId'] = ApiClient.convertToType(data['telemetryId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * telemetryId
 * @member {String} telemetryId
 */
StopBody.prototype['telemetryId'] = undefined;






export default StopBody;

