/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Point from './Point';

/**
 * The TelemetryResponseData model module.
 * @module model/TelemetryResponseData
 * @version TEL-1.2.5
 */
class TelemetryResponseData {
    /**
     * Constructs a new <code>TelemetryResponseData</code>.
     * @alias module:model/TelemetryResponseData
     */
    constructor() { 
        
        TelemetryResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TelemetryResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TelemetryResponseData} obj Optional instance to populate.
     * @return {module:model/TelemetryResponseData} The populated <code>TelemetryResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TelemetryResponseData();

            if (data.hasOwnProperty('telemetryId')) {
                obj['telemetryId'] = ApiClient.convertToType(data['telemetryId'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('operatorId')) {
                obj['operatorId'] = ApiClient.convertToType(data['operatorId'], 'String');
            }
            if (data.hasOwnProperty('aircraftId')) {
                obj['aircraftId'] = ApiClient.convertToType(data['aircraftId'], 'String');
            }
            if (data.hasOwnProperty('trackerId')) {
                obj['trackerId'] = ApiClient.convertToType(data['trackerId'], 'String');
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], [Point]);
            }
        }
        return obj;
    }


}

/**
 * Database telemetry id
 * @member {String} telemetryId
 */
TelemetryResponseData.prototype['telemetryId'] = undefined;

/**
 * Given title for telemetry (Title used in UI)
 * @member {String} title
 */
TelemetryResponseData.prototype['title'] = undefined;

/**
 * Owner of the telemetry entry
 * @member {String} operatorId
 */
TelemetryResponseData.prototype['operatorId'] = undefined;

/**
 * Aircraft id
 * @member {String} aircraftId
 */
TelemetryResponseData.prototype['aircraftId'] = undefined;

/**
 * Tracker device id
 * @member {String} trackerId
 */
TelemetryResponseData.prototype['trackerId'] = undefined;

/**
 * @member {Array.<module:model/Point>} points
 */
TelemetryResponseData.prototype['points'] = undefined;






export default TelemetryResponseData;

