/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * OpenAPI spec version: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListResponseDataEntry } from './ListResponseDataEntry';
import { HttpFile } from '../http/http';

export class ListResponseData {
    'telemetries'?: Array<ListResponseDataEntry>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "telemetries",
            "baseName": "telemetries",
            "type": "Array<ListResponseDataEntry>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListResponseData.attributeTypeMap;
    }
    
    public constructor() {
    }
}

