/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * OpenAPI spec version: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Point } from './Point';
import { HttpFile } from '../http/http';

export class ListResponseDataEntry {
    /**
    * Database telemetry id
    */
    'telemetryId'?: string;
    /**
    * Given title for telemetry (Title used in UI)
    */
    'title'?: string;
    /**
    * id of a specific drone
    */
    'aircraftId'?: string;
    /**
    * id of a specific tracker device
    */
    'trackerId'?: string;
    'points'?: Array<Point>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "telemetryId",
            "baseName": "telemetryId",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "aircraftId",
            "baseName": "aircraftId",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackerId",
            "baseName": "trackerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "Array<Point>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListResponseDataEntry.attributeTypeMap;
    }
    
    public constructor() {
    }
}

