/* tslint:disable */
/* eslint-disable */
/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DataResponseData,
    DataResponseDataFromJSON,
    DataResponseDataFromJSONTyped,
    DataResponseDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface DataResponse
 */
export interface DataResponse {
    /**
     * status
     * @type {string}
     * @memberof DataResponse
     */
    status: string;
    /**
     * message
     * @type {string}
     * @memberof DataResponse
     */
    message: string;
    /**
     * 
     * @type {DataResponseData}
     * @memberof DataResponse
     */
    data?: DataResponseData;
}

export function DataResponseFromJSON(json: any): DataResponse {
    return DataResponseFromJSONTyped(json, false);
}

export function DataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': !exists(json, 'data') ? undefined : DataResponseDataFromJSON(json['data']),
    };
}

export function DataResponseToJSON(value?: DataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': DataResponseDataToJSON(value.data),
    };
}


