/* tslint:disable */
/* eslint-disable */
/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Point,
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
} from './';

/**
 * 
 * @export
 * @interface DataBody
 */
export interface DataBody {
    /**
     * telemetryId
     * @type {string}
     * @memberof DataBody
     */
    telemetryId: string;
    /**
     * 
     * @type {Point}
     * @memberof DataBody
     */
    point: Point;
}

export function DataBodyFromJSON(json: any): DataBody {
    return DataBodyFromJSONTyped(json, false);
}

export function DataBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'telemetryId': json['telemetryId'],
        'point': PointFromJSON(json['point']),
    };
}

export function DataBodyToJSON(value?: DataBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'telemetryId': value.telemetryId,
        'point': PointToJSON(value.point),
    };
}


