/* tslint:disable */
/* eslint-disable */
/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartBody
 */
export interface StartBody {
    /**
     * Aircraft id to link your telemetry
     * @type {string}
     * @memberof StartBody
     */
    aircraftId: string;
    /**
     * Tracker id to link your telemetry
     * @type {string}
     * @memberof StartBody
     */
    trackerId: string;
}

export function StartBodyFromJSON(json: any): StartBody {
    return StartBodyFromJSONTyped(json, false);
}

export function StartBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aircraftId': json['aircraftId'],
        'trackerId': json['trackerId'],
    };
}

export function StartBodyToJSON(value?: StartBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aircraftId': value.aircraftId,
        'trackerId': value.trackerId,
    };
}


