/* tslint:disable */
/* eslint-disable */
/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartResponseData
 */
export interface StartResponseData {
    /**
     * telemetryId
     * @type {string}
     * @memberof StartResponseData
     */
    telemetryId: string;
    /**
     * Aircraft id linked to telemetry
     * @type {string}
     * @memberof StartResponseData
     */
    aircraftId?: string;
    /**
     * Tracker id linked to telemetry
     * @type {string}
     * @memberof StartResponseData
     */
    trackerId?: string;
}

export function StartResponseDataFromJSON(json: any): StartResponseData {
    return StartResponseDataFromJSONTyped(json, false);
}

export function StartResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'telemetryId': json['telemetryId'],
        'aircraftId': !exists(json, 'aircraftId') ? undefined : json['aircraftId'],
        'trackerId': !exists(json, 'trackerId') ? undefined : json['trackerId'],
    };
}

export function StartResponseDataToJSON(value?: StartResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'telemetryId': value.telemetryId,
        'aircraftId': value.aircraftId,
        'trackerId': value.trackerId,
    };
}


