/* tslint:disable */
/* eslint-disable */
/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopReponseData
 */
export interface StopReponseData {
    /**
     * New flight id for replay
     * @type {string}
     * @memberof StopReponseData
     */
    flightId: string;
    /**
     * Aircraft id linked to flight
     * @type {string}
     * @memberof StopReponseData
     */
    aircraftId?: string;
    /**
     * Tracker id linked to flight
     * @type {string}
     * @memberof StopReponseData
     */
    trackerId?: string;
}

export function StopReponseDataFromJSON(json: any): StopReponseData {
    return StopReponseDataFromJSONTyped(json, false);
}

export function StopReponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopReponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flightId': json['flightId'],
        'aircraftId': !exists(json, 'aircraftId') ? undefined : json['aircraftId'],
        'trackerId': !exists(json, 'trackerId') ? undefined : json['trackerId'],
    };
}

export function StopReponseDataToJSON(value?: StopReponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flightId': value.flightId,
        'aircraftId': value.aircraftId,
        'trackerId': value.trackerId,
    };
}


