/* tslint:disable */
/* eslint-disable */
/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopBody
 */
export interface StopBody {
    /**
     * telemetryId
     * @type {string}
     * @memberof StopBody
     */
    telemetryId: string;
}

export function StopBodyFromJSON(json: any): StopBody {
    return StopBodyFromJSONTyped(json, false);
}

export function StopBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'telemetryId': json['telemetryId'],
    };
}

export function StopBodyToJSON(value?: StopBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'telemetryId': value.telemetryId,
    };
}


