/* tslint:disable */
/* eslint-disable */
/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TelemetryResponseData,
    TelemetryResponseDataFromJSON,
    TelemetryResponseDataFromJSONTyped,
    TelemetryResponseDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface TelemetryResponse
 */
export interface TelemetryResponse {
    /**
     * status
     * @type {string}
     * @memberof TelemetryResponse
     */
    status: string;
    /**
     * message
     * @type {string}
     * @memberof TelemetryResponse
     */
    message: string;
    /**
     * 
     * @type {TelemetryResponseData}
     * @memberof TelemetryResponse
     */
    data?: TelemetryResponseData;
}

export function TelemetryResponseFromJSON(json: any): TelemetryResponse {
    return TelemetryResponseFromJSONTyped(json, false);
}

export function TelemetryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelemetryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
        'data': !exists(json, 'data') ? undefined : TelemetryResponseDataFromJSON(json['data']),
    };
}

export function TelemetryResponseToJSON(value?: TelemetryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': TelemetryResponseDataToJSON(value.data),
    };
}


