/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListResponseDataEntry from './ListResponseDataEntry';

/**
 * The ListResponseData model module.
 * @module model/ListResponseData
 * @version TEL-1.2.5
 */
class ListResponseData {
    /**
     * Constructs a new <code>ListResponseData</code>.
     * @alias module:model/ListResponseData
     */
    constructor() { 
        
        ListResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListResponseData} obj Optional instance to populate.
     * @return {module:model/ListResponseData} The populated <code>ListResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListResponseData();

            if (data.hasOwnProperty('telemetries')) {
                obj['telemetries'] = ApiClient.convertToType(data['telemetries'], [ListResponseDataEntry]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ListResponseDataEntry>} telemetries
 */
ListResponseData.prototype['telemetries'] = undefined;






export default ListResponseData;

