/**
 * Telemetry API
 * The telemetry API allows you to send realtime telemetry of your aircrafts into your IDRONECT account. It will help you to log your flights and allow you to automate your maintenance folow-up.
 *
 * The version of the OpenAPI document: TEL-1.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Point from './Point';

/**
 * The ListResponseDataEntry model module.
 * @module model/ListResponseDataEntry
 * @version TEL-1.2.5
 */
class ListResponseDataEntry {
    /**
     * Constructs a new <code>ListResponseDataEntry</code>.
     * @alias module:model/ListResponseDataEntry
     */
    constructor() { 
        
        ListResponseDataEntry.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListResponseDataEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListResponseDataEntry} obj Optional instance to populate.
     * @return {module:model/ListResponseDataEntry} The populated <code>ListResponseDataEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListResponseDataEntry();

            if (data.hasOwnProperty('telemetryId')) {
                obj['telemetryId'] = ApiClient.convertToType(data['telemetryId'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('aircraftId')) {
                obj['aircraftId'] = ApiClient.convertToType(data['aircraftId'], 'String');
            }
            if (data.hasOwnProperty('trackerId')) {
                obj['trackerId'] = ApiClient.convertToType(data['trackerId'], 'String');
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], [Point]);
            }
        }
        return obj;
    }


}

/**
 * Database telemetry id
 * @member {String} telemetryId
 */
ListResponseDataEntry.prototype['telemetryId'] = undefined;

/**
 * Given title for telemetry (Title used in UI)
 * @member {String} title
 */
ListResponseDataEntry.prototype['title'] = undefined;

/**
 * id of a specific drone
 * @member {String} aircraftId
 */
ListResponseDataEntry.prototype['aircraftId'] = undefined;

/**
 * id of a specific tracker device
 * @member {String} trackerId
 */
ListResponseDataEntry.prototype['trackerId'] = undefined;

/**
 * @member {Array.<module:model/Point>} points
 */
ListResponseDataEntry.prototype['points'] = undefined;






export default ListResponseDataEntry;

