on: [push, pull_request]

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ls
      - name: Publish package to npm
        uses: mikeal/merge-release@v4.0.7
